packages:
  - name: memelord
    environment:
      IMGFLIP_USERNAME: ${IMGFLIP_USERNAME}
      IMGFLIP_PASSWORD: ${IMGFLIP_PASSWORD}
    functions:
      - name: generate-meme
        runtime: nodejs:18
        main: simple.js
        limits:
          timeout: 30000
          memory: 256
        parameters:
          meme_template:
            type: string
            description: "The name of the meme template to use"
          meme_text:
            type: array
            description: "Array of text lines for the meme boxes"